#####################################################
## GIT WORKFLOW FOR CI/CD PIPELINE TERRAFORM SCANS ##
#####################################################

name: Terraform CI/CD Pipeline

permissions:
  contents: read

on:
  push:
    paths:
      - '**.tf'
  pull_request:
    paths:
      - '**.tf'

jobs:
  terraform_static_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

        # CREATE CLEAN EVIDENCE DIRECTORY
      - name: Prepare Report Directory
        run: |
          rm -rf reports
          mkdir -p reports
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.4

      - name: Terraform Format Check
        run: terraform fmt -check -recursive | tee reports/terraform-fmt.txt

      - name: Terraform Init (no backend)
        run: terraform init -backend=false | tee reports/terraform-init.txt

      - name: Terraform Validate
        run: terraform validate 2>&1 | tee reports/terraform-validate.txt

      - name: Install tflint
        uses: terraform-linters/setup-tflint@v4

      - name: Initialize tflint
        run: tflint --init

      - name: Run tflint (compact)
        run: |
          tflint -f compact 2>&1 | tee reports/tflint-compact.txt || true

      - name: Run tflint (JUnit)
        run: |
          tflint -f junit > reports/tflint-jsunit.xml || true

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov Scan (JUNIT)
        run: |
          checkov -d . -o junitxml --soft-fail > reports/checkov-junit.xml || true

      - name: Run Checkov Scan (JSON)
        run: |
          checkov -d . -o json --soft-fail > reports/checkov-json.txt || true

      - name: Upload Scan Results
        uses: actions/upload-artifact@v4
        with:
            name: ci-evidence
            path: reports/
            if-no-files-found: error